# Extension Jobs - Services Symfony
#
# Importer dans le module :
# imports:
#     - { resource: '../src/Extension/Jobs/config/services_jobs.yml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Repository des jobs
    WeprestaAcf\Wedev\Extension\Jobs\JobRepository:
        public: true

    # Dispatcher de jobs
    WeprestaAcf\Wedev\Extension\Jobs\JobDispatcher:
        public: true

    # Alias courts
    wedev.job_repository:
        alias: WeprestaAcf\Wedev\Extension\Jobs\JobRepository
        public: true

    wedev.job_dispatcher:
        alias: WeprestaAcf\Wedev\Extension\Jobs\JobDispatcher
        public: true

