# Extension Audit - Services Symfony
#
# Importer dans le module :
# imports:
#     - { resource: '../src/Extension/Audit/config/services_audit.yml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Repository d'audit
    WeprestaAcf\Wedev\Extension\Audit\AuditRepository:
        public: true

    # Logger d'audit
    WeprestaAcf\Wedev\Extension\Audit\AuditLogger:
        public: true

    # Alias courts
    wedev.audit_repository:
        alias: WeprestaAcf\Wedev\Extension\Audit\AuditRepository
        public: true

    wedev.audit_logger:
        alias: WeprestaAcf\Wedev\Extension\Audit\AuditLogger
        public: true

