# Extension Import - Services Symfony
#
# Importer dans le module :
# imports:
#     - { resource: '../src/Extension/Import/config/services_import.yml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Parsers
    WeprestaAcf\Wedev\Extension\Import\Parser\CsvParser:
        public: true

    WeprestaAcf\Wedev\Extension\Import\Parser\JsonParser:
        public: true

    WeprestaAcf\Wedev\Extension\Import\Parser\XmlParser:
        public: true

    # Alias courts
    wedev.parser.csv:
        alias: WeprestaAcf\Wedev\Extension\Import\Parser\CsvParser
        public: true

    wedev.parser.json:
        alias: WeprestaAcf\Wedev\Extension\Import\Parser\JsonParser
        public: true

    wedev.parser.xml:
        alias: WeprestaAcf\Wedev\Extension\Import\Parser\XmlParser
        public: true

