services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Media Extension
    WeprestaAcf\Wedev\Extension\Media\MediaExtension:
        public: true

    # Alias for easy access
    wedev.media:
        alias: WeprestaAcf\Wedev\Extension\Media\MediaExtension
        public: true

